---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2
provisioner:
  name: chef_zero
  client_rb:
    environments_path: 'test/integration/environments'
    environment: 'test'

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[7dtdserver::default]
    attributes:
