name '7dtdserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures 7dtdserver'
long_description 'Installs/Configures 7dtdserver'
version '0.1.0'
